# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

#Â r:
#   - oldrel
#   - release
#  - devel

os:
  - linux
  - osx

after_success:
  - Rscript -e 'covr::codecov(type="all")'
  

